apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: prometheus
  namespace: prometheus
spec:
  host: prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
