prometheus:
  prometheusSpec:
    podMonitorNamespaceSelector:
      matchLabels:
        # Only detect namespaces where istio-injection is enabled
        istio-injection: "enabled"
    podMonitorSelectorNilUsesHelmValues: false

prometheus-node-exporter:
  hostRootFsMount:
    enabled: false

crds:
  enabled: true

grafana:
  grafana.ini: |
    server:
      serve_from_sub_path: true
